#!/usr/bin/env python3

import curses
import os
import subprocess

show_hidden = False
curr = 0

def draw_listings(win, listings):
    global curr

    for i, listing in enumerate(listings):
        if i == curr:
            win.addstr(i, 0, listing, curses.A_REVERSE)
        else:
            win.addstr(i, 0, listing)

def draw_statusbar(win, cwd):
    global show_hidden

    status_text = cwd
    if show_hidden:
        status_text += " [.]"
    status_text += (" " * (curses.COLS - len(status_text)))
    win.addstr(curses.LINES - 2, 0, status_text, curses.A_REVERSE)

def getcurdir():
    curdir = os.getcwd()
    curdir = os.path.expanduser(curdir)
    curdir = os.path.normpath(curdir)
    return curdir

def getlistings(cwd):
    global show_hidden

    dirs = [x for x in os.listdir(cwd) if os.path.isdir(x)]
    files = [x for x in os.listdir(cwd) if os.path.isfile(x)]

    if not show_hidden:
        dirs = [x for x in dirs if not x.startswith(".")]
        files = [x for x in files if not x.startswith(".")]

    # first directories then files
    listings = dirs + files
    return listings

def key_handler(win, key, cwd, listings):
    global show_hidden
    global curr

    if key == "q":
        exit()
    elif key == ".":
        show_hidden = not show_hidden
    elif key == "j" and curr+1 < len(listings):
        curr += 1
    elif key == "k" and curr-1 > -1:
        curr -= 1
    elif key == "g":
        curr = 0
    elif key == "G":
        curr = len(listings) - 1
    elif key == "h":
        os.chdir("..")
        curr = 0
    elif key == "l":
        new = cwd + "/" + listings[curr]
        opener(win, new)

def opener(win, new):
    global curr

    if os.path.isdir(new):
        os.chdir(new)
        curr = 0
    else:
        curses.endwin()
        subprocess.call([os.environ["NFM_OPENER"], new])
        win.refresh()

def nfm(win = curses.initscr()):
    # ncurses settings
    curses.noecho()
    curses.cbreak()
    curses.curs_set(False)
    curses.use_default_colors()

    # main file-manager loop
    while True:
        cwd = getcurdir()
        win.clear()
        listings = getlistings(cwd)
        draw_listings(win, listings)
        draw_statusbar(win, cwd)
        key_handler(win, win.getkey(), cwd, listings)

curses.wrapper(nfm)
